# Generated by Django 3.2.9 on 2021-11-13 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 13, 14, 15, 20, 6180, tzinfo=utc), max_length=19),
        ),
    ]
