# Generated by Django 3.2.9 on 2021-11-13 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='country',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='detailed_desc',
            old_name='country',
            new_name='county',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 13, 15, 11, 24, 564249, tzinfo=utc), max_length=19),
        ),
    ]
