# Generated by Django 3.2.9 on 2021-11-13 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 13, 20, 27, 6, 969653, tzinfo=utc), max_length=19),
        ),
    ]
