# Generated by Django 3.2.9 on 2021-11-13 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20211114_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 13, 23, 12, 9, 229145, tzinfo=utc), max_length=19),
        ),
    ]
