# Generated by Django 3.2.9 on 2021-11-16 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20211116_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 16, 8, 28, 49, 637716, tzinfo=utc), max_length=19),
        ),
    ]
