# Generated by Django 3.2.9 on 2021-11-16 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='detailed_desc',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2021, 11, 16, 16, 14, 20, 324506, tzinfo=utc), max_length=19),
        ),
    ]
