# Generated by Django 4.0.2 on 2022-03-07 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0019_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 3, 7, 17, 44, 42, 191184, tzinfo=utc), max_length=19),
        ),
    ]
