# Generated by Django 4.0.2 on 2022-04-28 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0023_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 4, 28, 17, 33, 7, 134158, tzinfo=utc), max_length=19),
        ),
    ]
